name: student_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  http_parser: ^4.0.0
  dio: ^5.3.3
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.0
  intl: ^0.18.1
  multi_select_flutter: ^4.0.0
  file_picker: ^5.3.0
  flutter_hooks: ^0.20.5
  auto_route_generator: ^7.3.2
  get: ^4.6.6
  permission_handler: ^11.3.1
  socket_io_client: ^2.0.0
  freezed: ^2.5.2
  flutter_local_notifications: ^9.1.2
  flutter_isolate: ^2.0.0
  easy_localization: ^3.0.6
  google_fonts: ^6.2.1
  dropdown_search: ^5.0.6
  json_theme: ^6.4.0
  agora_uikit: ^1.3.10 
  flutter_tags: ^1.0.0-nullsafety.1
  flutter_material_pickers: ^3.6.0
  textfield_tags: ^3.0.1
  month_picker_dialog: ^2.11.2
  hydrated_bloc: ^9.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true
  assets:
    - lib/common/ui/assets/
    - lib/common/translations/
