name: student_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  http_parser: ^4.0.0
  dio: ^5.3.3
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true
